### ISSUE TITLE
Relabling blocked when using NoNewPrivileges 

### ISSUE THREAD

**Issue by cpuguy83** [projectatomic/container-selinux#45]
Creating a container with `NoNewPrivileges` and an selinux label causes the state transition to fail:

```
type=SELINUX_ERR msg=audit(1515446105.513:1559): op=security_bounded_transition seresult=denied oldcontext=system_u:system_r:container_runtime_t:s0 newcontext=system_u:system_r:spc_t:s0:c0,c1
type=SYSCALL msg=audit(1515446105.513:1559): arch=c000003e syscall=59 success=no exit=-1 a0=c4200d9670 a1=c420037910 a2=c42000dda0 a3=0 items=0 ppid=31738 pid=31748 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="runc:[2:INIT]" exe="/usr/bin/docker-runc" subj=system_u:system_r:container_runtime_t:s0 key=(null)
```

```
[root@localhost server]# rpm -qa | grep container-selinux
container-selinux-2.33-1.git86f33cd.el7.noarch
```

**Comment by wrabcak** [comment]
@rhatdan, We need to test this on Fedora. SELinux team added support for NoNewPrivileges + SELinux so we fix this by nnp_transition type.

**Comment by rhatdan** [comment]
@cpuguy83 You are doing this with a SPC_t container, which means that you are either compiling the docker without selinux support or you are running without --selinux-enabled in the docker daemon.

**Comment by cpuguy83** [comment]
@rhatdan I'm specifying this through crictl against cri-containerd, `spc_t` was just an example. `svirt_lxc_net_t` also fails in the same way... just happen to be using `docker-runc` as a final test to make sure I didn't mislabel the 'proper' runc.

**Comment by rhatdan** [comment]
Ok you are doing this on a RHEL or Centos system?

**Comment by cpuguy83** [comment]
Adding the custom typebounds rule shown in your [blog](https://danwalsh.livejournal.com/76220.html) works 

> Ok you are doing this on a RHEL or Centos system?

CentOS

**Comment by rhatdan** [comment]
I am working on typebounds on Fedora right now, I will back port fixes for RHEL

**Comment by rhatdan** [comment]
Ok it turns out that there are some big fixes for SELinux policy coming in RHEL7.5 which will make this a lot easier to handle.  I just updated container-selinux for Fedora 27 and Rawhide, to use the new nnp_transition feature.  But for now this is broken on Centos and RHEL.  You can add the typebounds to make it work.

**Comment by cpuguy83** [comment]
Thanks, Dan!
What are the implications of adding the necessary `typebounds` rules?

**Comment by rhatdan** [comment]
@cpuguy83 There is not security issue with adding them.  They basically just allow the transition, so that you are allowed to run spc_t or svirt_lxc_net_t (container_t) on your system.   I will update the next container-selinux for RHEL with the type bounds allowed, and see if it compiles correctly.

**Comment by rhatdan** [comment]
This is now fixed in Fedora and should be fixed in the next container-selinux update in RHEL.
